begin;
create temporary table plan_test_ids(label text primary key,id uuid default gen_random_uuid());
insert into plan_test_ids(label) values('owner'),('other'),('viewer'),('todo'),('milestone');
grant select on plan_test_ids to authenticated;
insert into auth.users(id,email) select id,id::text||'@planning-test.invalid' from plan_test_ids where label in ('owner','other','viewer');
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from plan_test_ids where label='owner'),true);
do $$ declare w uuid;p public.projects;t public.project_plan_items;first_item uuid;begin
 w:=public.ensure_workspace();p:=public.create_project(w,gen_random_uuid(),'{"name":"Plan test","next_action":"Original next action","next_action_due_on":"2026-10-05","start_date":"2026-10-01","target_date":"2026-10-20"}');
 if p.start_date<>'2026-10-01'::date then raise exception 'FAIL start date';end if;
 select id into first_item from public.project_plan_items where project_id=p.id and is_next;
 if first_item is null then raise exception 'FAIL legacy migration';end if;
 t:=public.save_plan_item(w,p.id,(select id from plan_test_ids where label='todo'),0,'{"kind":"TODO","title":"New next action","due_on":"2026-10-06","done":false,"is_next":true}');
 if (select count(*) from public.project_plan_items where project_id=p.id and is_next)<>1 then raise exception 'FAIL unique representative';end if;
 if (select next_action from public.projects where id=p.id)<>'New next action' then raise exception 'FAIL mirror';end if;
 if (select done from public.project_plan_items where id=first_item) then raise exception 'FAIL old task lost';end if;
 begin perform public.save_plan_item(w,p.id,t.id,99,'{"kind":"TODO","title":"Stale","due_on":null,"done":false,"is_next":false}');raise exception 'FAIL stale accepted';exception when serialization_failure then null;end;
 t:=public.save_plan_item(w,p.id,t.id,t.version,'{"kind":"TODO","title":"New next action","due_on":"2026-10-06","done":true,"is_next":false}');
 if (select next_action from public.projects where id=p.id)<>'' then raise exception 'FAIL complete mirror';end if;
 update public.projects set next_action='Edited through project',next_action_due_on='2026-10-08' where id=p.id;
 if not exists(select 1 from public.project_plan_items where project_id=p.id and is_next and title='Edited through project') then raise exception 'FAIL project sync';end if;
 begin update public.projects set start_date='2026-11-01' where id=p.id;raise exception 'FAIL date order';exception when check_violation then null;end;
 begin perform public.save_plan_item(w,p.id,(select id from plan_test_ids where label='milestone'),0,'{"kind":"MILESTONE","title":"Launch","due_on":null,"done":false,"is_next":false}');raise exception 'FAIL undated milestone';exception when check_violation then null;end;
 t:=public.save_plan_item(w,p.id,(select id from plan_test_ids where label='milestone'),0,'{"kind":"MILESTONE","title":"Launch","due_on":"2026-10-20","done":false,"is_next":false}');
 t:=public.save_plan_item(w,p.id,t.id,t.version,'{}',true);
 if t.deleted_at is null then raise exception 'FAIL soft removal';end if;
 begin update public.project_plan_items set title='Bypass';raise exception 'FAIL direct mutation';exception when insufficient_privilege then null;end;
 update public.projects set archived_at=now() where id=p.id;
 begin perform public.save_plan_item(w,p.id,gen_random_uuid(),0,'{"kind":"TODO","title":"Archived","due_on":null,"done":false,"is_next":false}');raise exception 'FAIL archive write';exception when insufficient_privilege then null;end;
 update public.projects set archived_at=null where id=p.id;
end $$;
select set_config('request.jwt.claim.sub',(select id::text from plan_test_ids where label='other'),true);
select public.ensure_workspace();
do $$ begin if exists(select 1 from public.project_plan_items) then raise exception 'FAIL tenant read';end if;end $$;
reset role;
insert into public.memberships(workspace_id,user_id,role) select w.id,t.id,'VIEWER' from public.workspaces w cross join plan_test_ids t where w.personal_owner_user_id=(select id from plan_test_ids where label='owner') and t.label='viewer';
set local role authenticated;
select set_config('request.jwt.claim.sub',(select id::text from plan_test_ids where label='viewer'),true);
do $$ declare p public.projects;begin
 select * into p from public.projects limit 1;if not exists(select 1 from public.project_plan_items) then raise exception 'FAIL viewer read';end if;
 begin perform public.save_plan_item(p.workspace_id,p.id,gen_random_uuid(),0,'{"kind":"TODO","title":"Forbidden","due_on":null,"done":false,"is_next":false}');raise exception 'FAIL viewer write';exception when insufficient_privilege then null;end;
end $$;
reset role;
select 'PASS: project dates, representative todo, bidirectional sync, completion, stale versions, milestone validation, soft removal, tenant isolation, viewer and archive restrictions' result;
rollback;
