'use client';
import {useState} from 'react';
import {useTranslations} from 'next-intl';
import {useForm,useWatch} from 'react-hook-form';
import * as Dialog from '@radix-ui/react-dialog';
import {Layers3,LayoutDashboard,FolderOpen,Plug,Settings,Plus,Search,List,LayoutGrid,Columns3,ArrowUpRight,ArrowRight,Clock3,Check,Archive,Trash2,X,Menu,LogOut,CheckCircle2,AlertCircle,ExternalLink,Link2} from 'lucide-react';
import {Link} from '@/i18n/navigation';
import {Preferences} from './preferences';
import {attention,blankProject,coordinations,dateInZone,freshness,projectInput,stages,statuses,type Project,type ProjectInput,type Source} from '@/modules/projects/domain';
type Modal={kind:'detail';id:string}|{kind:'edit';project?:Project}|{kind:'confirm';project:Project;action:'archive'|'trash'}|null;
type Section='overview'|'projects'|'integrations'|'settings';
export function Dashboard({initialProjects,demo,timezone}:{initialProjects:Project[];demo:boolean;timezone:string}){
 const t=useTranslations('Dashboard');const c=useTranslations('Common');const st=useTranslations('Status');const sg=useTranslations('Stage');const ft=useTranslations('Flag');const pt=useTranslations('Project');const er=useTranslations('Error');
 const [projects,setProjects]=useState(initialProjects);const [section,setSection]=useState<Section>('overview');
 const [view,setView]=useState<'list'|'grid'|'board'>('list');const [query,setQuery]=useState('');const [stage,setStage]=useState('');const [status,setStatus]=useState('');const [onlyAttention,setOnlyAttention]=useState(false);const [sort,setSort]=useState('recent');const [scope,setScope]=useState<'normal'|'archive'|'trash'>('normal');
 const [modal,setModal]=useState<Modal>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [mobileNav,setMobileNav]=useState(false);const [requestId,setRequestId]=useState('');
 const [now]=useState(()=>new Date());const today=dateInZone(now,timezone);
 const active=projects.filter(p=>!p.archived_at&&!p.deleted_at);
 const needs=active.filter(p=>attention(p,today).length).sort((a,b)=>{const order=['BLOCKED','OVERDUE','WAITING','DUE_SOON','NEEDS_INFO'];return order.indexOf(attention(a,today)[0])-order.indexOf(attention(b,today)[0]);});
 const filtered=projects.filter(p=>scope==='trash'?!!p.deleted_at:scope==='archive'?!!p.archived_at&&!p.deleted_at:!p.archived_at&&!p.deleted_at).filter(p=>(!stage||p.workflow_stage===stage)&&(!status||p.lifecycle_status===status)&&(!onlyAttention||attention(p,today).length>0)&&`${p.name} ${p.description} ${p.owner_label} ${p.next_action} ${p.project_sources.map(s=>s.external_name).join(' ')}`.toLocaleLowerCase().includes(query.toLocaleLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):sort==='due'?(a.target_date??'9999').localeCompare(b.target_date??'9999'):b.last_activity_at.localeCompare(a.last_activity_at));
 const selected=modal?.kind==='detail'?projects.find(p=>p.id===modal.id):undefined;
 function update(p:Project){setProjects(old=>old.some(x=>x.id===p.id)?old.map(x=>x.id===p.id?p:x):[p,...old]);}
 async function jsonRequest(url:string,method:string,body:unknown){const res=await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const json=await res.json();if(!res.ok)throw new Error(json.error??'saveFailed');return json;}
 function openNew(){setRequestId(crypto.randomUUID());setError('');setModal({kind:'edit'});}
 async function save(input:ProjectInput,existing?:Project){
  setBusy(true);setError('');try{
   if(demo){update({...existing,...input,id:existing?.id??crypto.randomUUID(),workspace_id:'demo',version:(existing?.version??0)+1,created_at:existing?.created_at??now.toISOString(),confirmed_at:new Date().toISOString(),last_activity_at:new Date().toISOString(),archived_at:null,deleted_at:null,project_sources:existing?.project_sources??[]});}
   else{const result=existing?await jsonRequest(`/api/projects/${existing.id}`,'PATCH',{type:'edit',version:existing.version,project:input}):await jsonRequest('/api/projects','POST',{request_id:requestId,project:input});update(result.project);}
   setModal(null);setNotice(pt('changesSaved'));
  }catch(e){setError(e instanceof Error?e.message:'saveFailed');}finally{setBusy(false);}
 }
 async function mutate(p:Project,type:'archive'|'trash'|'restore'|'completeAction'){
  setBusy(true);setError('');try{
   if(demo)update({...p,version:p.version+1,...(type==='archive'?{archived_at:now.toISOString()}:type==='trash'?{deleted_at:now.toISOString()}:type==='restore'?{archived_at:null,deleted_at:null}:{next_action:'',next_action_due_on:null})});
   else update((await jsonRequest(`/api/projects/${p.id}`,'PATCH',{type,version:p.version})).project);
   setModal(null);setNotice(pt('changesSaved'));
  }catch(e){setError(e instanceof Error?e.message:'saveFailed');}finally{setBusy(false);}
 }
 async function addSource(p:Project,data:{external_name:string;canonical_url:string;role:string}){
  setBusy(true);setError('');try{const source:Source=demo?{...data,id:crypto.randomUUID()}:(await jsonRequest('/api/sources','POST',{...data,project_id:p.id})).source;update({...p,project_sources:[...p.project_sources,source]});setNotice(pt('changesSaved'));}catch(e){setError(e instanceof Error?e.message:'saveFailed');}finally{setBusy(false);}
 }
 const nav=[{key:'overview' as const,icon:LayoutDashboard},{key:'projects' as const,icon:FolderOpen},{key:'integrations' as const,icon:Plug},{key:'settings' as const,icon:Settings}];
 const projectTile=(p:Project)=>{const flags=attention(p,today);return <button className='project-tile' key={p.id} onClick={()=>{setError('');setModal({kind:'detail',id:p.id});}}><span className={`project-mark mark-${stages.indexOf(p.workflow_stage)%4}`}><FolderOpen size={20}/></span><span className={`status-dot status-${p.lifecycle_status}`}>{st(p.lifecycle_status)}</span><h3>{p.name}</h3><p>{p.description||c('unknown')}</p><div className='tile-step'><ArrowRight size={15}/>{p.next_action||c('unknown')}</div><footer><span>{sg(p.workflow_stage)}</span><span>{p.target_date||'—'}</span></footer>{flags[0]&&<span className={`flag flag-${flags[0]}`}>{ft(flags[0])}</span>}</button>;};
 return <div className='workspace-shell'><a className='skip-link' href='#main'>{t('overview')}</a>
  <aside className={`sidebar ${mobileNav?'mobile-open':''}`}><Link href={demo?'/demo':'/dashboard'} className='brand'><span className='brand-icon'><Layers3 size={23}/></span>Project Hub</Link><button className='mobile-close icon-button' aria-label={c('close')} onClick={()=>setMobileNav(false)}><X/></button><div className='workspace-picker'><span className='workspace-avatar'>P</span><div><strong>{t('workspace')}</strong><small>{t('personal')}</small></div></div><div className='nav-label'>WORKSPACE</div><nav>{nav.map(n=><button key={n.key} className={section===n.key?'active':''} onClick={()=>{setSection(n.key);setMobileNav(false);}}><n.icon size={19}/>{t(n.key)}</button>)}</nav><div className='sidebar-bottom'><div className='sidebar-note'><Layers3 size={24}/><p>{t('tagline')}</p><span>{t('nextStep')}</span></div><span className='connection-label'><i/>{demo?t('demoMode'):t('connected')}</span>{demo?<Link className='sidebar-login' href='/login'>{t('login')}<ArrowUpRight size={16}/></Link>:<button className='signout' onClick={async()=>{await fetch('/api/auth/signout',{method:'POST'});window.location.reload();}}><LogOut size={16}/>{t('signout')}</button>}</div></aside>
  <div className='workspace-body'><header className='topbar'><div className='breadcrumbs'><button className='mobile-menu icon-button' aria-label={t('workspace')} onClick={()=>setMobileNav(true)}><Menu/></button><span>{t('workspace')}</span><span>/</span><strong>{t(section)}</strong></div><Preferences/></header>
   <main id='main' className='main-content'>
    {demo&&<div className='demo-banner'><span><strong>{t('demo')}</strong><small>{t('demoHint')}</small></span><Link href='/login'>{t('login')}<ArrowUpRight size={15}/></Link></div>}
    <div className='feedback' aria-live='polite'>{notice}</div>
    {(section==='overview'||section==='projects')?<>
     <div className='page-heading'><div><span className='eyebrow'>{t('eyebrow')}</span><h1>{t('title')}</h1><p>{t('description')}</p></div><button className='button primary' onClick={openNew}><Plus size={18}/>{t('new')}</button></div>
     {section==='overview'&&<><div className='stats'>{[{label:'total',value:active.length,icon:FolderOpen},{label:'active',value:active.filter(p=>['BUILDING','LIVE'].includes(p.lifecycle_status)).length,icon:Layers3},{label:'attention',value:needs.length,icon:Clock3},{label:'completed',value:active.filter(p=>p.lifecycle_status==='COMPLETED').length,icon:CheckCircle2}].map((item,i)=><button className={`stat glass stat-${i}`} key={item.label} onClick={()=>{setScope('normal');setStatus(i===3?'COMPLETED':'');setOnlyAttention(i===2);}}><span><item.icon size={18}/>{t(item.label)}</span><strong>{String(item.value).padStart(2,'0')}</strong><ArrowUpRight className='stat-arrow' size={17}/></button>)}</div>
     <section className='attention-panel glass'><div className='section-heading'><div><h2><span className='attention-indicator'/>{t('attention')}<span className='count-pill'>{needs.length}</span></h2><p>{t('attentionHint')}</p></div></div>{needs.length?<div className='attention-items'>{needs.slice(0,3).map(p=><button key={p.id} onClick={()=>setModal({kind:'detail',id:p.id})}><span className={`flag flag-${attention(p,today)[0]}`}>{ft(attention(p,today)[0])}</span><strong>{p.name}</strong><p>{p.coordination_state!=='CLEAR'?p.coordination_note:p.next_action||c('unknown')}</p><ArrowUpRight size={17}/></button>)}</div>:<div className='calm-empty'><CheckCircle2/><div><strong>{t('allClear')}</strong><p>{t('allClearHint')}</p></div></div>}</section></>}
     <section className='projects-panel glass'><div className='section-heading'><div className='title-with-count'><h2>{t('allProjects')}</h2><span>{t('count',{count:filtered.length})}</span></div><div className='view-toggle'>{([{key:'list',icon:List},{key:'grid',icon:LayoutGrid},{key:'board',icon:Columns3}] as const).map(v=><button key={v.key} className={view===v.key?'selected':''} aria-label={t(v.key)} aria-pressed={view===v.key} onClick={()=>setView(v.key)}><v.icon size={17}/></button>)}</div></div>
      <div className='scope-tabs'>{(['normal','archive','trash'] as const).map(s=><button key={s} className={scope===s?'selected':''} onClick={()=>setScope(s)}>{t(s)}</button>)}</div>
      <div className='filters'><label className='search-box'><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t('search')} aria-label={t('search')}/></label><select aria-label={t('allStages')} value={stage} onChange={e=>setStage(e.target.value)}><option value=''>{t('allStages')}</option>{stages.map(s=><option key={s} value={s}>{sg(s)}</option>)}</select><select aria-label={t('allStatuses')} value={status} onChange={e=>setStatus(e.target.value)}><option value=''>{t('allStatuses')}</option>{statuses.map(s=><option key={s} value={s}>{st(s)}</option>)}</select><select aria-label={t('recent')} value={sort} onChange={e=>setSort(e.target.value)}><option value='recent'>{t('recent')}</option><option value='name'>{t('nameSort')}</option><option value='due'>{t('dueSort')}</option></select><button className={`filter-attention ${onlyAttention?'selected':''}`} aria-pressed={onlyAttention} onClick={()=>setOnlyAttention(v=>!v)}><AlertCircle size={16}/>{t('attentionOnly')}</button></div>
      {!filtered.length?<div className='empty-state'><FolderOpen size={38}/><h3>{projects.length?t('noResults'):t('empty')}</h3><p>{t('emptyHint')}</p>{projects.length?<button className='button secondary' onClick={()=>{setQuery('');setStage('');setStatus('');setOnlyAttention(false);}}>{t('reset')}</button>:<button className='button primary' onClick={openNew}><Plus size={16}/>{t('new')}</button>}</div>:view==='list'?<div className='project-table'><div className='table-header'><span>{t('name')}</span><span>{t('stage')}</span><span>{t('owner')}</span><span>{t('nextAction')}</span><span>{t('due')}</span><span/></div>{filtered.map((p,i)=><button className='project-row' key={p.id} onClick={()=>{setError('');setModal({kind:'detail',id:p.id});}}><span className='project-identity'><span className={`project-mark mark-${i%4}`}><FolderOpen size={18}/></span><span><strong>{p.name}</strong><small>{st(p.lifecycle_status)}{freshness(p.confirmed_at,now)==='STALE'&&<span className='stale-dot'> · {pt('freshness')}</span>}</small></span></span><span className='stage-badge'>{sg(p.workflow_stage)}</span><span className='owner-cell'>{p.owner_label&&<span className='owner-avatar'>{p.owner_label.slice(0,1)}</span>}{p.owner_label||c('unassigned')}</span><span className='next-cell'>{p.next_action||'—'}{attention(p,today)[0]&&<small className={`flag flag-${attention(p,today)[0]}`}>{ft(attention(p,today)[0])}</small>}</span><span className='date-cell'>{p.target_date||'—'}</span><ArrowUpRight size={16}/></button>)}</div>:view==='grid'?<div className='project-grid'>{filtered.map(projectTile)}</div>:<div className='board'>{stages.map(s=><section className='board-column' key={s}><h3>{sg(s)}<span>{filtered.filter(p=>p.workflow_stage===s).length}</span></h3>{filtered.filter(p=>p.workflow_stage===s).map(projectTile)}</section>)}</div>}
     </section><footer className='page-footer'><span>Project Hub</span><span>{t('activityHint')}</span></footer>
    </>:section==='integrations'?<><div className='page-heading'><div><span className='eyebrow'>CONNECTED TOOLS</span><h1>{t('integrationTitle')}</h1><p>{t('integrationDescription')}</p></div></div><div className='integration-grid'>{['Notion','GitHub','Vercel'].map((name,i)=><article className='glass integration-card' key={name}><span className={`project-mark mark-${i}`}>{name[0]}</span><h2>{name}</h2><p>{t('notConnected')}</p><span className='stage-badge'>{t('manualAvailable')}</span></article>)}</div></>:<section className='glass settings-panel'><h1>{t('settingsTitle')}</h1><p>{t('settingsDescription')}</p><dl><dt>{t('timezone')}</dt><dd>{timezone}</dd><dt>{t('authority')}</dt><dd>{t('hubAuthority')}</dd></dl><Preferences/></section>}
   </main>
  </div>
  <Dialog.Root open={!!modal} onOpenChange={open=>{if(!open&&!busy){setModal(null);setError('');}}}><Dialog.Portal><Dialog.Overlay className='dialog-overlay'/><Dialog.Content className={`dialog-content glass ${modal?.kind==='edit'?'wide':''}`}><Dialog.Close asChild><button className='dialog-close icon-button' aria-label={c('close')} disabled={busy}><X size={20}/></button></Dialog.Close>
   {modal?.kind==='edit'?<><Dialog.Title>{modal.project?pt('edit'):pt('create')}</Dialog.Title><Dialog.Description>{pt('intro')}</Dialog.Description><ProjectForm key={modal.project?.id??'new'} project={modal.project} busy={busy} onSave={save}/></>:selected?<><Dialog.Title>{selected.name}</Dialog.Title><Dialog.Description>{selected.description||t('nextStep')}</Dialog.Description><div className='detail-badges'><span className='stage-badge'>{sg(selected.workflow_stage)}</span><span className='status-dot'>{st(selected.lifecycle_status)}</span></div><dl className='detail-fields'><dt>{pt('owner')}</dt><dd>{selected.owner_label||c('unassigned')}</dd><dt>{pt('nextAction')}</dt><dd>{selected.next_action||c('unknown')}</dd><dt>{pt('targetDate')}</dt><dd>{selected.target_date||c('unknown')}</dd><dt>{pt('reason')}</dt><dd>{selected.coordination_note||'—'}</dd><dt>{pt('freshness')}</dt><dd><FreshnessLabel project={selected} now={now}/></dd></dl><div className='detail-actions'>{selected.archived_at||selected.deleted_at?<button className='button primary' disabled={busy} onClick={()=>mutate(selected,'restore')}>{pt('restore')}</button>:<><button className='button primary' onClick={()=>setModal({kind:'edit',project:selected})}>{c('edit')}</button>{selected.next_action&&<button className='button secondary' disabled={busy} onClick={()=>mutate(selected,'completeAction')}><Check size={16}/>{pt('completeAction')}</button>}</>}</div><div className='sources-section'><h3><Link2 size={17}/>{t('sourceLabel')}</h3>{selected.project_sources.length?selected.project_sources.map(s=><a key={s.id} href={s.canonical_url} target='_blank' rel='noopener noreferrer' className='source-link'>{s.external_name}<ExternalLink size={15}/></a>):<p>{t('noSource')}</p>}{!selected.archived_at&&!selected.deleted_at&&<SourceForm busy={busy} onAdd={data=>addSource(selected,data)}/>}</div>{!selected.deleted_at&&<div className='danger-actions'>{!selected.archived_at&&<button onClick={()=>setModal({kind:'confirm',project:selected,action:'archive'})}><Archive size={15}/>{pt('archive')}</button>}<button onClick={()=>setModal({kind:'confirm',project:selected,action:'trash'})}><Trash2 size={15}/>{pt('trash')}</button></div>}</>:modal?.kind==='confirm'?<><Dialog.Title>{pt(modal.action)}</Dialog.Title><Dialog.Description>{pt('dangerHint')}</Dialog.Description><p className='confirm-name'>{modal.project.name}</p><button className='button primary' disabled={busy} onClick={()=>mutate(modal.project,modal.action)}>{pt('confirm')}</button></>:null}
   {error&&<p role='alert' className='error-message'>{er.has(error)?er(error):er('saveFailed')}</p>}
  </Dialog.Content></Dialog.Portal></Dialog.Root>
 </div>;
}
function FreshnessLabel({project,now}:{project:Project;now:Date}){const t=useTranslations('Freshness');return <span>{t(freshness(project.confirmed_at,now))}</span>;}
function ProjectForm({project,busy,onSave}:{project?:Project;busy:boolean;onSave:(input:ProjectInput,existing?:Project)=>Promise<void>}){
 const t=useTranslations('Project');const c=useTranslations('Common');const st=useTranslations('Status');const sg=useTranslations('Stage');const co=useTranslations('Coordination');
 const {register,handleSubmit,setValue,control,getValues}=useForm<ProjectInput>({defaultValues:project?Object.fromEntries(Object.keys(blankProject).map(k=>[k,project[k as keyof ProjectInput]])) as ProjectInput:blankProject});
 const [invalid,setInvalid]=useState(false);const currentStatus=useWatch({control,name:'lifecycle_status'});
 return <form className='project-form' onSubmit={handleSubmit(async values=>{const parsed=projectInput.safeParse(values);if(!parsed.success){setInvalid(true);return;}setInvalid(false);await onSave(parsed.data,project);})}><label className='full'>{t('name')}<input {...register('name')} required maxLength={120} placeholder={t('namePlaceholder')}/></label><label className='full'>{t('description')}<textarea {...register('description')} maxLength={2000} rows={2}/></label><label>{t('status')}<select {...register('lifecycle_status')} onChange={e=>{const v=e.target.value as ProjectInput['lifecycle_status'];setValue('lifecycle_status',v);if(v==='COMPLETED'){setValue('workflow_stage','CLOSED');setValue('next_action','');setValue('next_action_due_on',null);}else if(getValues('workflow_stage')==='CLOSED')setValue('workflow_stage','DISCOVERY');}}>{statuses.map(s=><option key={s} value={s}>{st(s)}</option>)}</select></label><label>{t('stage')}<select {...register('workflow_stage')} onChange={e=>{const v=e.target.value as ProjectInput['workflow_stage'];setValue('workflow_stage',v);if(v==='CLOSED'){setValue('lifecycle_status','COMPLETED');setValue('next_action','');setValue('next_action_due_on',null);}else if(getValues('lifecycle_status')==='COMPLETED')setValue('lifecycle_status','BUILDING');}}>{stages.map(s=><option key={s} value={s}>{sg(s)}</option>)}</select></label><label>{t('owner')}<input {...register('owner_label')} maxLength={100}/></label><label>{t('targetDate')}<input type='date' {...register('target_date')}/></label><label className='full'>{t('nextAction')}<input {...register('next_action')} maxLength={300}/></label><label>{t('nextDue')}<input type='date' {...register('next_action_due_on')}/></label><label>{t('coordination')}<select {...register('coordination_state')}>{coordinations.map(s=><option key={s} value={s}>{co(s)}</option>)}</select></label><label className='full'>{t('reason')}<textarea {...register('coordination_note')} maxLength={500} rows={2}/></label>{currentStatus==='COMPLETED'&&<p className='full form-hint'>{t('cancelActionHint')}</p>}{invalid&&<p className='full error-message' role='alert'>{t('validation')}</p>}<div className='form-footer full'><button className='button primary' disabled={busy} type='submit'>{busy?c('saving'):c('save')}<ArrowRight size={16}/></button></div></form>;
}
function SourceForm({busy,onAdd}:{busy:boolean;onAdd:(data:{external_name:string;canonical_url:string;role:string})=>Promise<void>}){
 const t=useTranslations('Project');const r=useTranslations('Role');const [open,setOpen]=useState(false);
 return <div className='source-form-wrap'><button className='text-button' onClick={()=>setOpen(v=>!v)}><Plus size={15}/>{t('addSource')}</button>{open&&<form className='source-form' onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;const data=new FormData(form);await onAdd({external_name:String(data.get('external_name')),canonical_url:String(data.get('canonical_url')),role:String(data.get('role'))});}}><label>{t('sourceName')}<input name='external_name' required maxLength={120}/></label><label>{t('sourceUrl')}<input name='canonical_url' required type='url' pattern='https?://.*' maxLength={2048}/></label><label>{t('sourceRole')}<select name='role'>{['PLANNING','DESIGN','EXECUTION','DEPLOYMENT','OTHER'].map(role=><option key={role} value={role}>{r(role)}</option>)}</select></label><button className='button secondary' disabled={busy}>{t('addSource')}</button></form>}</div>;
}