 'use client';
import {useEffect,useRef,useState} from 'react';
import {useLocale} from 'next-intl';
import {Plug,Plus,Search,Check,ExternalLink,RefreshCw,Unplug,Link2,ArrowRight,X} from 'lucide-react';
import {providers,findBinding,type Provider,type Connection,type ExternalItem,type SourceBinding,type Scope} from '@/modules/integrations/domain';
import {blankProject,type Project} from '@/modules/projects/domain';
const names={GITHUB:'GitHub',VERCEL:'Vercel',NOTION:'Notion'};
const demoConnections:Connection[]=[['GITHUB','개인 개발 계정','personal',''],['GITHUB','팀 개발 계정','studio',''],['VERCEL','스튜디오 배포','studio','team-demo'],['NOTION','기획 워크스페이스','planning','workspace-demo']].map(([provider,label,account_id,scope_id],i)=>({id:`demo-connection-${i}`,workspace_id:'demo',owner_user_id:'demo',provider:provider as Provider,account_id,scope_id,label,account_label:account_id,scope_label:scope_id||'GitHub App',version:1,connected_at:'2026-10-01T00:00:00Z',disconnected_at:null}));
function demoCatalog(c:Connection):ExternalItem[]{const labels=c.provider==='GITHUB'?['projecthub','brand-website','walking-map']:c.provider==='VERCEL'?['projecthub-preview','brand-website','walking-map']:['Project Hub 기획','브랜드 리뉴얼 회의록','프로젝트 데이터베이스'];return labels.map((name,i)=>({external_id:`demo-${c.provider}-${i}`,kind:c.provider==='GITHUB'?'repository':c.provider==='VERCEL'?'project':i===2?'data_source':'page',scope:c.scope_id||'demo',name,description:'둘러보기용 예시 항목입니다.',url:c.provider==='GITHUB'?`https://github.com/example/${name}`:c.provider==='VERCEL'?`https://vercel.com/example/${name}`:'https://www.notion.so',metadata:{example:true},ticket:`demo-${i}`}));}
async function call(url:string,method='GET',body?:unknown){const r=await fetch(url,{method,...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw new Error(d.error??'saveFailed');return d;}
type Props={demo:boolean;projects:Project[];onProject:(p:Project)=>void;onOpen:(id:string)=>void;result?:string};
export function Integrations({demo,projects,onProject,onOpen,result}:Props){
 const ko=useLocale()==='ko';const say=(a:string,b:string)=>ko?a:b;
 const [connections,setConnections]=useState<Connection[]>(demo?demoConnections:[]);const [bindings,setBindings]=useState<SourceBinding[]>([]);const [configured,setConfigured]=useState<Partial<Record<Provider,boolean>>>({});const [installUrl,setInstallUrl]=useState<string|null>(null);
 const [loading,setLoading]=useState(!demo);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState(result==='success'?'connected':result==='failed'?'oauthFailed':'');
 const [adding,setAdding]=useState<Provider|null>(null);const [label,setLabel]=useState('');const [renaming,setRenaming]=useState<Connection|null>(null);const [disconnect,setDisconnect]=useState<Connection|null>(null);
 const [active,setActive]=useState<Connection|null>(null);const [scopes,setScopes]=useState<Scope[]>([]);const [scope,setScope]=useState('');const [items,setItems]=useState<ExternalItem[]>([]);const [cursor,setCursor]=useState<string|null>(null);const [query,setQuery]=useState('');const [appliedQuery,setAppliedQuery]=useState('');const [selection,setSelection]=useState<Record<string,string>>({});const [preview,setPreview]=useState(false);const request=useRef(0);const lock=useRef(false);const catalogHeading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{if(active)catalogHeading.current?.focus();},[active,preview]);
 const available=projects.filter(p=>!p.archived_at&&!p.deleted_at);const selected=items.filter(i=>Object.hasOwn(selection,i.external_id));
 useEffect(()=>{if(demo)return;const controller=new AbortController();fetch('/api/integrations',{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error();return r.json();}).then(d=>{if(controller.signal.aborted)return;setConnections(d.connections);setBindings(d.bindings);setConfigured(d.configured);setInstallUrl(d.githubInstallUrl);}).catch(()=>{if(!controller.signal.aborted)setError('loadFailed');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[demo]);
 async function reload(){if(demo)return;const d=await call('/api/integrations');setConnections(d.connections);setBindings(d.bindings);setConfigured(d.configured);setInstallUrl(d.githubInstallUrl);}
 async function run(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await action();}catch(e){setError(e instanceof Error?e.message:'saveFailed');}finally{lock.current=false;setBusy(false);}}
 async function catalog(c:Connection,scopeId:string,page='',search='',append=false){const version=++request.current;const d=demo?{items:demoCatalog(c),cursor:null}:await call(`/api/integrations/catalog?${new URLSearchParams({connection_id:c.id,scope:scopeId,cursor:page,query:search})}`);if(version!==request.current)return;setItems(old=>append?[...old,...d.items.filter((i:ExternalItem)=>!old.some(o=>o.external_id===i.external_id))]:d.items);setCursor(d.cursor);}
 function browse(c:Connection){void run(async()=>{setActive(c);setItems([]);setSelection({});setPreview(false);setQuery('');setAppliedQuery('');setScopes([]);setCursor(null);const d=demo?{scopes:[{id:c.scope_id||'demo',name:c.scope_label||c.account_label}]}:await call(`/api/integrations/catalog?connection_id=${c.id}&scopes=1`);setScopes(d.scopes);const scopeId=d.scopes[0]?.id??'';setScope(scopeId);if(d.scopes.length)await catalog(c,scopeId);});}
 function connect(){if(!adding)return;void run(async()=>{if(demo){const existing=connections.find(c=>c.provider===adding&&c.disconnected_at);if(existing)setConnections(old=>old.map(c=>c.id===existing.id?{...c,disconnected_at:null,version:c.version+1}:c));else setConnections(old=>[...old,{...demoConnections.find(c=>c.provider===adding)!,id:crypto.randomUUID(),label:label.trim(),account_label:label.trim(),account_id:crypto.randomUUID()}]);setAdding(null);setNotice('demoConnected');}else{const d=await call('/api/integrations/connect','POST',{provider:adding,label:label.trim(),locale:ko?'ko':'en'});window.location.assign(d.url);}});}
 function editConnection(c:Connection,isDisconnect:boolean){void run(async()=>{if(demo){setConnections(old=>old.map(v=>v.id===c.id?{...v,label:isDisconnect?v.label:label.trim(),version:v.version+1,disconnected_at:isDisconnect?new Date().toISOString():v.disconnected_at}:v));if(isDisconnect)setBindings(old=>old.map(s=>s.connection_id===c.id?{...s,sync_status:'DISCONNECTED'}:s));}else{await call('/api/integrations','PATCH',{id:c.id,version:c.version,label:isDisconnect?c.label:label.trim(),disconnect:isDisconnect});await reload();}if(active?.id===c.id){setActive(null);setItems([]);setSelection({});}setRenaming(null);setDisconnect(null);setNotice(isDisconnect?'disconnected':'saved');});}
 function importSelected(){if(!active)return;void run(async()=>{if(demo){const nextBindings=[...bindings];const changed=new Map<string,Project>();for(const item of selected){if(findBinding(nextBindings,active.provider,item.external_id))continue;const target=selection[item.external_id];const now=new Date().toISOString();const p=changed.get(target)||projects.find(p=>p.id===target)||{...blankProject,id:crypto.randomUUID(),workspace_id:'demo',name:item.name,description:item.description,version:1,created_at:now,confirmed_at:now,last_activity_at:now,archived_at:null,deleted_at:null,project_sources:[]};const s:SourceBinding={id:crypto.randomUUID(),project_id:p.id,provider:active.provider,connection_id:active.id,external_id:item.external_id,external_kind:item.kind,external_scope:item.scope,external_name:item.name,canonical_url:item.url,sync_status:'OK',last_synced_at:now,metadata:item.metadata};nextBindings.push(s);changed.set(p.id,{...p,project_sources:[...p.project_sources,{id:s.id,external_name:s.external_name,canonical_url:s.canonical_url,role:active.provider==='NOTION'?'PLANNING':active.provider==='VERCEL'?'DEPLOYMENT':'EXECUTION'}]});}changed.forEach(onProject);setBindings(nextBindings);}else{const d=await call('/api/integrations/import','POST',{connection_id:active.id,items:selected.map(i=>({ticket:i.ticket,project_id:selection[i.external_id]||null}))});d.projects.forEach(onProject);await reload();}setSelection({});setPreview(false);setNotice('imported');});}
 function sync(s:SourceBinding){void run(async()=>{if(demo)setBindings(old=>old.map(b=>b.id===s.id?{...b,last_synced_at:new Date().toISOString(),sync_status:'OK'}:b));else{try{const d=await call('/api/integrations/sync','POST',{source_id:s.id});onProject(d.project);}finally{await reload();}}setNotice('synced');});}
 const errors:Record<string,string>={notConfigured:say('연동 앱 설정이 필요합니다.','Configure the integration app first.'),appUrlMismatch:say('현재 접속 주소와 NEXT_PUBLIC_APP_URL이 다릅니다. 등록한 주소로 접속해 주세요.','Open the app at its configured NEXT_PUBLIC_APP_URL.'),reconnectRequired:say('연결 권한이 없거나 만료되었습니다. 계정을 다시 연결해 주세요.','Access expired or was revoked. Reconnect the account.'),rateLimited:say('외부 서비스 요청 한도에 도달했습니다. 잠시 후 다시 시도하세요.','Provider rate limit reached. Try again later.'),selectionExpired:say('선택 목록이 만료되었습니다. 목록을 다시 열어 선택해 주세요.','Selection expired. Reopen the catalog.'),alreadyLinked:say('이미 다른 프로젝트에 연결된 항목입니다.','Already linked to another project.'),sourceUnavailable:say('원본에 접근할 수 없습니다. 기존 자료는 유지됩니다.','Source unavailable. Existing data is preserved.'),conflict:say('연결 정보가 변경되었습니다. 새로고침 후 다시 시도하세요.','Connection changed. Refresh and try again.')};
 const notices:Record<string,string>={connected:say('계정을 연결했습니다. 가져올 항목을 선택하세요.','Account connected. Select items to import.'),oauthFailed:say('계정 연결을 완료하지 못했습니다. 앱 설정과 승인 범위를 확인한 후 다시 연결하세요.','Connection failed. Check app settings and permissions, then reconnect.'),demoConnected:say('예시 계정이 추가되었습니다. 실제 외부 계정은 연결하지 않습니다.','Example account added. No external account was connected.'),saved:say('연결 이름을 저장했습니다.','Connection name saved.'),disconnected:say('Hub 연결을 해제했습니다. 프로젝트와 참조 링크는 유지됩니다.','Disconnected from Hub. Projects and references are preserved.'),imported:say('선택한 항목을 프로젝트에 연결했습니다.','Selected items linked to projects.'),synced:say('선택한 원본의 최신 정보를 가져왔습니다.','Refreshed this selected source.')};
 return <section className='integrations-workspace'><div className='page-heading'><div><span className='eyebrow'>CONNECTED TOOLS</span><h1>{say('필요한 연결만, 한곳에','Your tools, selectively connected')}</h1><p>{say('여러 계정을 연결하고, 원하는 항목만 프로젝트에 묶으세요.','Connect multiple accounts and bring only the items you choose.')}</p></div></div>
 {demo&&<p className='integration-note'>{say('예시 계정과 목록으로 가져오기 흐름을 체험합니다. 변경은 새로고침하면 초기화됩니다.','Try the import flow with example accounts. Reloading resets changes.')}</p>}
 {notice&&<p role='status' className='integration-notice'>{notices[notice]}</p>}{error&&<p role='alert' className='error-message'>{errors[error]||say('처리하지 못했습니다. 연결 상태를 확인하고 다시 시도하세요.','Could not complete the request. Check your connection and retry.')} <button disabled={busy} className='text-button' onClick={()=>void run(reload)}>{say('다시 불러오기','Reload')}</button></p>}
 {loading&&<p role='status'>{say('연결 정보를 불러오는 중…','Loading connections…')}</p>}
 <div className='integration-grid'>{providers.map(provider=><article className='glass integration-provider' key={provider}><div className='integration-provider-heading'><span className={`project-mark mark-${providers.indexOf(provider)}`}>{names[provider][0]}</span><h2>{names[provider]}</h2><span>{connections.filter(c=>c.provider===provider&&!c.disconnected_at).length}</span></div><p>{provider==='GITHUB'?say('계정·조직별 허용한 저장소','Authorized repositories by account and organization'):provider==='VERCEL'?say('계정·팀별 프로젝트와 배포 상태','Projects and deployment status by account and team'):say('워크스페이스별 허용한 페이지·데이터베이스','Authorized pages and databases by workspace')}</p><button className='button secondary' disabled={busy||(!demo&&!configured[provider])} onClick={()=>{setAdding(provider);setRenaming(null);setLabel('');}}><Plus size={16}/>{say('계정 연결 추가','Add connection')}</button>{!demo&&!configured[provider]&&<small>{say('연동 앱 설정 필요','App setup required')}</small>}{provider==='GITHUB'&&installUrl&&<a className='text-button' href={installUrl} target='_blank' rel='noopener noreferrer'>{say('저장소 접근 범위 설정','Manage repository access')} ↗</a>}</article>)}</div>
 {(adding||renaming)&&<form className='glass integration-connect-form' onSubmit={e=>{e.preventDefault();if(renaming)editConnection(renaming,false);else connect();}}><h3>{renaming?say('연결 이름 변경','Rename connection'):`${adding?names[adding]:''} · ${say('계정 연결','Connect account')}`}</h3><label>{say('구분할 이름','Connection label')}<input autoFocus value={label} maxLength={160} required placeholder={say('예: 개인 계정 / 고객사 A / 기획팀','e.g. Personal / Client A / Planning team')} onChange={e=>setLabel(e.target.value)}/></label><p>{say('계정·팀·워크스페이스 범위는 서비스 승인 화면과 실제 응답으로 확인합니다.','Account, team and workspace identity is verified by the provider.')}</p><div className='integration-actions'><button type='button' className='button secondary' disabled={busy} onClick={()=>{setAdding(null);setRenaming(null);}}>{say('취소','Cancel')}</button><button className='button primary' disabled={busy||!label.trim()}>{renaming?say('저장','Save'):demo?say('예시 계정 추가','Add example account'):say('승인 화면으로','Continue to authorization')}<ArrowRight size={15}/></button></div></form>}
 {disconnect&&<div className='glass integration-connect-form' role='alert'><h3>{disconnect.label} · {say('연결 해제','Disconnect')}</h3><p>{say('저장한 인증정보를 삭제하고 새 수신을 중단합니다. Hub 프로젝트와 기존 자료는 남습니다. 외부 서비스의 앱 승인 철회는 해당 서비스 설정에서 별도로 할 수 있습니다.','Delete stored credentials and stop fetching. Hub projects remain. You can separately revoke app authorization at the provider.')}</p><div className='integration-actions'><button className='button secondary' disabled={busy} onClick={()=>setDisconnect(null)}>{say('취소','Cancel')}</button><button className='button primary' disabled={busy} onClick={()=>editConnection(disconnect,true)}>{say('연결 해제','Disconnect')}</button></div></div>}
 <section className='glass integration-connections'><h2><Plug size={20}/>{say('내 연결','My connections')}</h2>{!loading&&!connections.length&&<p>{say('아직 연결된 계정이 없습니다.','No connected accounts yet.')}</p>}{connections.map(c=><article key={c.id} className={`integration-account ${active?.id===c.id?'selected':''}`}><div><strong>{c.label}</strong><p>{names[c.provider]} · {c.account_label} · {c.scope_label}</p><small>{c.disconnected_at?say('연결 해제됨','Disconnected'):say('선택한 항목만 가져오기 · 읽기 연동','Selective import · Read integration')}</small></div><div className='integration-actions'>{!c.disconnected_at&&<button className='button primary' disabled={busy} onClick={()=>browse(c)}><Search size={15}/>{say('목록에서 선택','Browse & select')}</button>}<button className='button secondary' disabled={busy} onClick={()=>{setRenaming(c);setAdding(null);setLabel(c.label);}}>{say('이름 변경','Rename')}</button>{!c.disconnected_at&&<button className='icon-button' disabled={busy} aria-label={`${c.label} ${say('연결 해제','Disconnect')}`} onClick={()=>setDisconnect(c)}><Unplug size={17}/></button>}</div></article>)}</section>
 {active&&<section className='glass integration-catalog'><div className='integration-section-heading'><div><span className='eyebrow'>{names[active.provider]} · {active.label}</span><h2 ref={catalogHeading} tabIndex={-1}>{say('가져올 항목 선택','Choose what to bring')}</h2></div><button className='icon-button' disabled={busy} aria-label={say('목록 닫기','Close catalog')} onClick={()=>{setActive(null);setSelection({});}}><X/></button></div><p>{say('선택 전에는 프로젝트를 만들지 않습니다. 각 항목의 연결 대상을 지정하세요.','Nothing is imported until you select and confirm a destination.')}</p>
 {!preview&&<><form className='integration-search' onSubmit={e=>{e.preventDefault();setSelection({});setAppliedQuery(query);void run(()=>catalog(active,scope,'',query));}}><label>{say('조직·워크스페이스','Organization / workspace')}<select disabled={busy} value={scope} onChange={e=>{setScope(e.target.value);setSelection({});setAppliedQuery(query);void run(()=>catalog(active,e.target.value,'',query));}}>{scopes.map(s=><option value={s.id} key={s.id}>{active.provider==='GITHUB'?s.name:active.scope_label}</option>)}</select></label><label>{say('이름 검색','Search by name')}<input value={query} disabled={busy} onChange={e=>setQuery(e.target.value)} placeholder={say('찾는 항목 이름','Item name')}/></label><button className='button secondary' disabled={busy||!scopes.length}><Search size={16}/>{say('검색','Search')}</button></form>{active.provider==='GITHUB'&&<small>{say('불러온 저장소 목록 안에서 검색합니다. 더 보기를 눌러 다음 목록도 확인하세요.','Search filters loaded repositories. Load more to check additional results.')}</small>}
 {!busy&&!scopes.length&&<p className='planning-empty'>{say('접근 가능한 설치 범위가 없습니다. GitHub App을 원하는 계정·저장소에 설치한 후 다시 연결하세요.','No accessible installation. Install the GitHub App on the desired account and repositories, then reconnect.')}</p>}
 <div className='integration-items'>{items.filter(i=>i.name.toLocaleLowerCase().includes(query.toLocaleLowerCase())).map(item=>{const linked=findBinding(bindings,active.provider,item.external_id);const checked=Object.hasOwn(selection,item.external_id);return <article key={item.external_id} className={`integration-item ${checked?'selected':''}`}><label className='integration-item-choice'><input type='checkbox' checked={checked} disabled={busy||!!linked||(!checked&&selected.length>=20)} onChange={e=>setSelection(old=>{const next={...old};if(e.target.checked)next[item.external_id]='';else delete next[item.external_id];return next;})}/><span><strong>{item.name}</strong><small>{item.kind} · {item.description||item.scope}</small></span></label>{linked?<button className='text-button' onClick={()=>onOpen(linked.project_id)}><Check size={14}/>{say('연결됨','Linked')} · {projects.find(p=>p.id===linked.project_id)?.name||say('프로젝트','Project')}</button>:checked?<label className='integration-target'>{say('연결 대상','Destination')}<select disabled={busy} value={selection[item.external_id]} onChange={e=>setSelection(old=>({...old,[item.external_id]:e.target.value}))}><option value=''>{say('새 프로젝트로 만들기','Create new project')}</option>{available.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>:null}<a href={item.url} target='_blank' rel='noopener noreferrer' aria-label={`${item.name} ${say('원본 열기','Open source')}`}><ExternalLink size={16}/></a></article>;})}</div>{!busy&&!items.length&&!!scopes.length&&<p className='planning-empty'>{say('허용된 항목이 없습니다. 서비스의 공유·설치 범위를 확인하세요.','No authorized items. Check sharing and installation access.')}</p>}{cursor&&<button className='button secondary' disabled={busy} onClick={()=>void run(()=>catalog(active,scope,cursor,appliedQuery,true))}>{say('더 보기','Load more')}</button>}<div className='integration-actions integration-import-bar'><span>{selected.length} / 20 {say('선택','selected')}</span><button className='button primary' disabled={busy||!selected.length} onClick={()=>setPreview(true)}>{say('가져오기 미리보기','Preview import')}<ArrowRight size={16}/></button></div></>}
 {preview&&<div className='integration-preview'><h3>{say('이 항목만 가져옵니다','Only these items will be imported')}</h3>{selected.map(i=><article key={i.external_id}><strong>{i.name}</strong><ArrowRight size={16}/><span>{selection[i.external_id]?projects.find(p=>p.id===selection[i.external_id])?.name:say('새 프로젝트','New project')}</span></article>)}<p>{say('이름·설명·참조 링크·상태 요약을 가져옵니다. 기존 프로젝트의 업무 상태나 투두는 덮어쓰지 않습니다.','Imports name, description, reference and source status. Existing project tasks and workflow state stay under your control.')}</p><div className='integration-actions'><button className='button secondary' disabled={busy} onClick={()=>setPreview(false)}>{say('선택 수정','Edit selection')}</button><button className='button primary' disabled={busy||!selected.length} onClick={importSelected}>{busy?say('가져오는 중…','Importing…'):say('선택 항목 가져오기','Import selected')}</button></div></div>}
 </section>}
 <section className='glass integration-connections'><h2><Link2 size={20}/>{say('연결한 원본','Linked sources')}</h2><p>{say('필요한 항목만 최신 정보를 받습니다. 프로젝트의 업무 상태는 직접 관리합니다.','Refresh only what you linked. Manage project workflow independently.')}</p>{!bindings.length&&<p className='planning-empty'>{say('목록에서 원하는 항목을 선택하면 여기에 표시됩니다.','Selected sources will appear here.')}</p>}{bindings.map(s=><article key={s.id} className='integration-account'><div><strong>{s.external_name}</strong><p>{names[s.provider as Provider]} · {connections.find(c=>c.id===s.connection_id)?.label||say('다른 멤버의 연결','Another member’s connection')}</p><button className='text-button' onClick={()=>onOpen(s.project_id)}>{projects.find(p=>p.id===s.project_id)?.name||say('프로젝트 보기','View project')}</button><small>{s.sync_status==='DISCONNECTED'?say('연결 해제 · 기존 정보 보존','Disconnected · Previous data preserved'):s.sync_status==='ERROR'?say('갱신 필요 · 기존 정보 보존','Refresh needed · Previous data preserved'):say('마지막 수신','Last received')} {s.last_synced_at?new Date(s.last_synced_at).toLocaleString(ko?'ko-KR':'en'):''}</small>{Object.entries(s.metadata).filter(([,v])=>v!==null&&v!==''&&v!==false).map(([k,v])=><small key={k}>{({framework:say('프레임워크','Framework'),deployment_status:say('배포 상태','Deployment'),repository:say('저장소','Repository'),default_branch:say('기본 브랜치','Default branch'),visibility:say('공개 범위','Visibility'),language:say('언어','Language'),pushed_at:say('최근 푸시','Last push'),last_edited_time:say('원본 수정','Source edited'),example:say('예시 데이터','Example')} as Record<string,string>)[k]||k}: {String(v)}</small>)}</div><button className='button secondary' disabled={busy||s.sync_status==='DISCONNECTED'||!connections.some(c=>c.id===s.connection_id&&!c.disconnected_at)||!available.some(p=>p.id===s.project_id)} onClick={()=>sync(s)}><RefreshCw size={15}/>{say('최신 정보 받기','Refresh')}</button></article>)}</section>
 <section className='glass integration-other'><h2>{say('다른 도구도 프로젝트에','Other tools belong here, too')}</h2><p>{say('Figma, Google Drive, Linear 등은 프로젝트의 원본 링크로 연결할 수 있습니다. 자동 연동은 서비스별 지원을 추가할 때 제공됩니다.','Connect Figma, Google Drive, Linear and other tools as project reference links. Automated connectors can be added separately.')}</p><div className='integration-actions'>{available.length>0?<select aria-label={say('링크를 추가할 프로젝트','Project to add a link')} defaultValue='' onChange={e=>{if(e.target.value)onOpen(e.target.value);e.target.value='';}}><option value=''>{say('프로젝트를 골라 링크 추가','Choose a project to add a link')}</option>{available.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select>:<span>{say('프로젝트를 먼저 만들어 주세요.','Create a project first.')}</span>}</div></section>
 </section>;
}
