'use client';
import {useEffect,useState} from 'react';
import {useLocale,useTranslations} from 'next-intl';
import * as Dialog from '@radix-ui/react-dialog';
import {FileText,LoaderCircle,X} from 'lucide-react';
import {blankProject,coordinations,projectInput,stages,statuses,type Project} from '@/modules/projects/domain';
import {fields,type Candidate,type Draft} from '@/modules/drafts/domain';

const copy={ko:{title:'회의록에서 프로젝트 만들기',intro:'회의록을 붙여넣고, 근거를 확인한 뒤 프로젝트로 만드세요.',text:'회의록 또는 텍스트',date:'회의 날짜 (선택)',source:'원문 URL (선택)',privacy:'추출 시 입력 내용을 OpenAI로 전송합니다. 앱은 원문 전체를 저장하지 않으며, 후보와 근거만 암호화해 최대 24시간 보관합니다. 확정·취소 시 삭제합니다. 제공자의 데이터 보관 정책이 별도로 적용됩니다.',extract:'후보 추출',sample:'예시로 검토 화면 체험',demo:'데모에서는 예시 후보만 체험할 수 있습니다. 입력한 내용은 외부로 전송되지 않습니다.',unavailable:'AI 추출 설정이 아직 완료되지 않았습니다. 직접 프로젝트 생성은 계속 사용할 수 있습니다.',review:'후보를 선택하고 수정하세요',defaults:'미정 항목에는 기본값을 제안했습니다. 근거를 확인하고 수정하세요.',evidence:'원문 근거',unconfirmed:'미확정 / 기본 제안',none:'프로젝트 후보를 찾지 못했습니다. 프로젝트 이름과 할 일을 포함해 다시 입력하세요.',overflow:'10개를 초과하는 후보가 있습니다. 나머지는 텍스트를 나누어 입력하세요.',save:'선택한 프로젝트 생성',cancel:'취소하고 닫기',back:'다시 입력',keep:'원문 URL을 프로젝트에 함께 저장',duplicate:'비슷한 기존 프로젝트',error:'처리하지 못했습니다. 입력을 확인한 뒤 다시 시도하세요.',expired:'초안이 만료됐습니다. 다시 추출해 주세요.',limit:'추출 사용량 한도에 도달했습니다. 잠시 후 다시 시도하세요.',select:'이 후보 생성',links:'확인된 원문 링크',busy:'처리 중…'},en:{title:'Create projects from notes',intro:'Paste meeting notes, review the evidence, then create projects.',text:'Meeting notes or text',date:'Meeting date (optional)',source:'Source URL (optional)',privacy:'Extraction sends your input to OpenAI. This app does not store the full text. Candidates and evidence are encrypted for up to 24 hours and deleted on confirmation or cancellation. Provider retention policies apply separately.',extract:'Extract candidates',sample:'Try a sample review',demo:'The demo uses sample candidates only. Your input is not sent to any provider.',unavailable:'AI extraction is not configured yet. You can still create projects manually.',review:'Select and edit candidates',defaults:'Unknown fields use suggested defaults. Check the evidence before saving.',evidence:'Source evidence',unconfirmed:'Unconfirmed / suggested default',none:'No project candidates found. Include project names and next actions, then try again.',overflow:'More than 10 candidates found. Split the remaining notes into another request.',save:'Create selected projects',cancel:'Cancel and close',back:'Enter new notes',keep:'Save the source URL with projects',duplicate:'Similar existing project',error:'Unable to complete the request. Check the input and try again.',expired:'This draft expired. Extract again.',limit:'Extraction quota reached. Please try again later.',select:'Create this candidate',links:'Verified source links',busy:'Working…'}};

export function TextProjects({demo,projects,onCreated}:{demo:boolean;projects:Project[];onCreated:(projects:Project[])=>void}){
 const locale=useLocale();const t=copy[locale==='ko'?'ko':'en'];const p=useTranslations('Project');const stageT=useTranslations('Stage');const statusT=useTranslations('Status');const coordinationT=useTranslations('Coordination');
 const [open,setOpen]=useState(false);const [text,setText]=useState('');const [date,setDate]=useState('');const [source,setSource]=useState('');
 const [draft,setDraft]=useState<Draft|null>(null);const [selected,setSelected]=useState<string[]>([]);const [keep,setKeep]=useState(false);
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [available,setAvailable]=useState(false);
 useEffect(()=>{if(open&&!demo){let active=true;fetch('/api/drafts').then(r=>r.json()).then(r=>{if(active)setAvailable(r.available===true);}).catch(()=>{});return()=>{active=false;};}},[open,demo]);
 const label=(f:string)=>({name:p('name'),description:p('description'),lifecycle_status:p('status'),workflow_stage:p('stage'),owner_label:p('owner'),next_action:p('nextAction'),next_action_due_on:p('nextDue'),target_date:p('targetDate'),coordination_state:p('coordination'),coordination_note:p('reason')}[f]??f);
 async function call(url:string,body:unknown){const response=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error);return data;}
 async function discard(close:boolean){if(busy)return;setBusy(true);setError('');try{if(draft&&!demo)await call('/api/drafts/cancel',{draft_id:draft.id});setDraft(null);setSelected([]);if(close){setOpen(false);setText('');setSource('');setDate('');}}catch{setError(t.error);}finally{setBusy(false);}}
 function sample(){const name=locale==='ko'?'브랜드 웹사이트 개편':'Brand website redesign';const action=locale==='ko'?'첫 화면 시안 검토':'Review homepage mockups';const owner=locale==='ko'?'지민':'Jimin';const note=`${name}\n${owner}: ${action}`;const c:Candidate={candidate_id:crypto.randomUUID(),project:{...blankProject,name,owner_label:owner,next_action:action},evidence:[{field:'name',quote:name},{field:'owner_label',quote:owner},{field:'next_action',quote:action}],unconfirmed:['lifecycle_status','workflow_stage','target_date'],links:[]};setText(note);setDraft({id:crypto.randomUUID(),expires_at:new Date(Date.now()+86400000).toISOString(),candidates:[c],source_url:null,overflow:false});setSelected([c.candidate_id]);setError('');}
 async function run(){setBusy(true);setError('');try{const d:Draft=await call('/api/drafts',{text,meeting_date:date||null,source_url:source||null});setDraft(d);setSelected(d.candidates.map(c=>c.candidate_id));}catch(e){setError(e instanceof Error&&e.message==='extractionLimit'?t.limit:t.error);}finally{setBusy(false);}}
 function edit(id:string,f:string,value:string){setDraft(d=>d?{...d,candidates:d.candidates.map(c=>c.candidate_id===id?{...c,project:{...c.project,[f]:value||((f==='target_date'||f==='next_action_due_on')?null:'')}}:c)}:d);}
 async function confirm(){if(!draft||!selected.length)return;const candidates=draft.candidates.filter(c=>selected.includes(c.candidate_id));if(candidates.some(c=>!projectInput.safeParse(c.project).success)){setError(t.error);return;}if(Date.parse(draft.expires_at)<=Date.now()){setError(t.expired);return;}setBusy(true);setError('');try{
  const created=demo?candidates.map(c=>({...c.project,id:crypto.randomUUID(),workspace_id:'demo',version:1,created_at:new Date().toISOString(),confirmed_at:new Date().toISOString(),last_activity_at:new Date().toISOString(),archived_at:null,deleted_at:null,project_sources:[]})): (await call('/api/drafts/confirm',{draft_id:draft.id,keep_source:keep,candidates:candidates.map(c=>({candidate_id:c.candidate_id,project:c.project}))})).projects;
  onCreated(created);setDraft(null);setText('');setSelected([]);setOpen(false);
 }catch{setError(t.error);}finally{setBusy(false);}}
 return <Dialog.Root open={open} onOpenChange={value=>{if(value){setOpen(true);setError('');}else void discard(true);}}><Dialog.Trigger asChild><button className='button secondary'><FileText size={18}/>{t.title}</button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className='dialog-overlay'/><Dialog.Content className='dialog-content glass text-project-dialog' onEscapeKeyDown={e=>{if(busy)e.preventDefault();}} onPointerDownOutside={e=>e.preventDefault()}>
  <Dialog.Title>{t.title}</Dialog.Title><Dialog.Description>{t.intro}</Dialog.Description><button className='icon-button dialog-close' aria-label={t.cancel} disabled={busy} onClick={()=>void discard(true)}><X/></button>
  <p className='draft-privacy'>{demo?t.demo:t.privacy} {!demo&&<a href='https://developers.openai.com/api/docs/guides/your-data' target='_blank' rel='noreferrer'>OpenAI ↗</a>}</p>
  {!draft?<div className='draft-input'><label>{t.text}<textarea rows={9} value={text} onChange={e=>setText(e.target.value)} maxLength={40000}/></label><small>{[...text].length.toLocaleString()} / 20,000</small><div className='draft-meta'><label>{t.date}<input type='date' value={date} onChange={e=>setDate(e.target.value)}/></label><label>{t.source}<input type='url' value={source} onChange={e=>setSource(e.target.value)}/></label></div>{!demo&&!available&&<p role='status'>{t.unavailable}</p>}<div className='detail-actions'>{demo?<button className='button primary' onClick={sample}>{t.sample}</button>:<button className='button primary' disabled={busy||!available||!text.trim()||[...text].length>20000} onClick={run}>{busy?<LoaderCircle size={18}/>:<FileText size={18}/>} {busy?t.busy:t.extract}</button>}</div></div>:<>
   <h3 className='draft-review-title'>{t.review}</h3><p>{t.defaults}</p>{draft.overflow&&<p className='error-message'>{t.overflow}</p>}{!draft.candidates.length&&<p role='status'>{t.none}</p>}
   {draft.candidates.map(c=><section className='draft-candidate' key={c.candidate_id}><label className='draft-select'><input type='checkbox' checked={selected.includes(c.candidate_id)} disabled={busy} onChange={e=>setSelected(ids=>e.target.checked?[...ids,c.candidate_id]:ids.filter(id=>id!==c.candidate_id))}/><strong>{c.project.name}</strong><span>{t.select}</span></label>
    {projects.filter(x=>!x.deleted_at&&x.name.toLocaleLowerCase().includes(c.project.name.toLocaleLowerCase())).map(x=><p className='draft-warning' key={x.id}>{t.duplicate}: {x.name}</p>)}
    <div className='draft-fields'>{fields.map(f=><label key={f}>{label(f)}{c.unconfirmed.includes(f)&&<small>{t.unconfirmed}</small>}{f==='lifecycle_status'||f==='workflow_stage'||f==='coordination_state'?<select value={c.project[f]} disabled={busy} onChange={e=>edit(c.candidate_id,f,e.target.value)}>{(f==='lifecycle_status'?statuses:f==='workflow_stage'?stages:coordinations).map(v=><option key={v} value={v}>{f==='lifecycle_status'?statusT(v):f==='workflow_stage'?stageT(v):coordinationT(v)}</option>)}</select>:<input type={f.endsWith('_on')||f==='target_date'?'date':'text'} value={c.project[f]??''} disabled={busy} onChange={e=>edit(c.candidate_id,f,e.target.value)}/>}</label>)}</div>
    <details><summary>{t.evidence} ({c.evidence.length})</summary>{c.evidence.map((e,i)=><blockquote key={i}><strong>{label(e.field)}</strong><p>{e.quote}</p></blockquote>)}</details>{c.links.length>0&&<div><small>{t.links}</small>{c.links.map(l=><a className='source-link' key={l.url} href={l.url} target='_blank' rel='noreferrer'>{l.name} ↗</a>)}</div>}
   </section>)}
   {draft.source_url&&<label className='draft-select'><input type='checkbox' checked={keep} onChange={e=>setKeep(e.target.checked)}/>{t.keep}</label>}
   <div className='draft-footer'><button className='button secondary' disabled={busy} onClick={()=>void discard(false)}>{t.back}</button><button className='button primary' disabled={busy||!selected.length} onClick={confirm}>{busy?t.busy:`${t.save} (${selected.length})`}</button></div>
  </>}{error&&<p role='alert' className='error-message'>{error}</p>}
 </Dialog.Content></Dialog.Portal></Dialog.Root>;
}
