import {describe,it,expect} from 'vitest';
import {blankProject,projectInput,type Project} from '@/modules/projects/domain';
import {calendarEntries,monthDays,moveMonth,planInput,syncDemoNext,todoMatches,type PlanItem} from './domain';
const p:Project={...blankProject,id:'p',workspace_id:'w',name:'Test',start_date:'2026-10-01',target_date:'2026-10-10',version:1,created_at:'2026-10-01T00:00:00Z',last_activity_at:'2026-10-01T00:00:00Z',confirmed_at:'2026-10-01T00:00:00Z',archived_at:null,deleted_at:null,project_sources:[]};
const item:PlanItem={id:'a',workspace_id:'w',project_id:'p',title:'Review',kind:'TODO',due_on:'2026-10-03',done:false,is_next:false,created_at:p.created_at,updated_at:p.created_at,version:1,deleted_at:null};
describe('shared calendar and todos',()=>{
 it('builds leap-year and cross-year months without timezone shifts',()=>{expect(monthDays('2028-02')).toContain('2028-02-29');expect(monthDays('2026-10')).toHaveLength(42);expect(monthDays('2026-10')[0]).toBe('2026-09-27');expect(moveMonth('2026-12',1)).toBe('2027-01');});
 it('includes starts, targets and dated items, not undated or archived items',()=>{const events=calendarEntries([p,{...p,id:'archived',archived_at:p.created_at}],[item,{...item,id:'no-date',due_on:null},{...item,id:'archived-item',project_id:'archived'}]);expect(events.map(e=>e.kind)).toEqual(['START','TODO','TARGET']);});
 it('separates overdue, today, future, undated and completed work',()=>{expect(todoMatches(item,'today','2026-10-03')).toBe(true);expect(todoMatches(item,'overdue','2026-10-03')).toBe(false);expect(todoMatches(item,'overdue','2026-10-04')).toBe(true);expect(todoMatches({...item,done:true},'open','2026-10-03')).toBe(false);expect(todoMatches({...item,due_on:null},'undated','2026-10-03')).toBe(true);});
 it('prevents a completed todo or milestone from becoming next action',()=>{expect(planInput.safeParse({...item,kind:'TODO'}).success).toBe(false);expect(planInput.safeParse({kind:'TODO',title:'X',due_on:null,done:true,is_next:true}).success).toBe(false);expect(planInput.safeParse({kind:'MILESTONE',title:'X',due_on:null,done:false,is_next:false}).success).toBe(false);});
 it('rejects a project target before its start',()=>expect(projectInput.safeParse({...blankProject,name:'X',start_date:'2026-10-10',target_date:'2026-10-01'}).success).toBe(false));
 it('updates one demo representative without duplication and retains completed history',()=>{let items=syncDemoNext([],{...p,next_action:'Review'});const id=items[0].id;items=syncDemoNext(items,{...p,next_action:'Review again'});expect(items).toHaveLength(1);expect(items[0].id).toBe(id);expect(items[0].title).toBe('Review again');items=syncDemoNext(items,{...p,next_action:''});expect(items[0].done).toBe(true);expect(items[0].is_next).toBe(false);items=syncDemoNext(items,{...p,next_action:'New work'});expect(items).toHaveLength(2);expect(items[1].id).not.toBe(id);});
});
