import {describe,it,expect} from 'vitest';
import {normalizeGithub,normalizeVercel,normalizeNotion,identity,safeUrl,importInput,vercelCompletionUrl} from './domain';
describe('selective integrations',()=>{
 it('uses stable provider IDs independently of account or display name',()=>{expect(identity('GITHUB','42')).toBe(identity('GITHUB','42'));expect(identity('GITHUB','42')).not.toBe(identity('VERCEL','42'));});
 it('normalizes only allowed GitHub metadata, never tokens or arbitrary fields',()=>{const r=normalizeGithub({id:42,full_name:'team/repo',html_url:'https://github.com/team/repo',token:'SECRET',owner:{login:'team'},private:true});expect(r.external_id).toBe('42');expect(r.metadata.visibility).toBe('private');expect(JSON.stringify(r)).not.toContain('SECRET');});
 it('preserves Notion data-source identity and extracts title without copying body',()=>{const r=normalizeNotion({id:'12345678-1234-1234-1234-123456789abc',object:'data_source',title:[{plain_text:'Plan'}],parent:{database_id:'db'},blocks:['PRIVATE BODY']});expect(r.external_id).toBe('12345678123412341234123456789abc');expect(r.kind).toBe('data_source');expect(r.metadata.database_id).toBe('db');expect(JSON.stringify(r)).not.toContain('PRIVATE BODY');});
 it('does not carry Vercel environment variables into Hub',()=>{const r=normalizeVercel({id:'prj_one',name:'app',env:[{value:'SECRET'}],targets:{production:{url:'app.example.com',readyState:'READY'}}},'team_one');expect(r.metadata.deployment_status).toBe('READY');expect(JSON.stringify(r)).not.toContain('SECRET');});
 it('rejects unsafe external URLs and malformed IDs',()=>{expect(safeUrl('javascript:alert(1)','https://example.com')).toBe('https://example.com');expect(safeUrl('https://secret:token@example.com','https://example.com')).toBe('https://example.com');expect(()=>normalizeGithub({id:'../bad'})).toThrow();expect(()=>normalizeNotion({id:'bad'})).toThrow();});
 it('allows Vercel installation completion only on its exact HTTPS origin',()=>{expect(vercelCompletionUrl('https://vercel.com/integrations/setup')).toBe('https://vercel.com/integrations/setup');for(const url of ['https://vercel.com.evil.example/','http://vercel.com/','https://secret@vercel.com/','javascript:alert(1)'])expect(vercelCompletionUrl(url)).toBeNull();});
 it('requires explicit, bounded selections',()=>{expect(importInput.safeParse({connection_id:'12345678-1234-4234-8234-123456789abc',items:[]}).success).toBe(false);expect(importInput.safeParse({connection_id:'12345678-1234-4234-8234-123456789abc',items:[{ticket:'signed',project_id:null}]}).success).toBe(true);});
});
